# Site settings
title: SYSUCC_XiaZhao
description: 'Main Page'
url: 'https://zhaoxia413.github.io'
baseurl: ''
profilepic: '/images/me.jpeg'
bkimage: '/images/mybk.jpeg'
google_analytics: UA-12345-67
font_awesome: 'fontawesome.js'

author:
  name: 'SYSUCC_XiaZhao'
  email: zhaoxia1@sysucc.org.cn
#   twitter_username: zhaoxia
#  facebook_username: joshgerdes
  github_username: zhaoxia413.github.io
#   linkedin_username:  zhaoxia413
#   meetup_name: zhaoxia413

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
